ALTER TABLE Users
DROP CONSTRAINT [PK__Users__3214EC07D157AAD0];

ALTER TABLE Users
ADD CONSTRAINT PK_Id
PRIMARY KEY (Id);

ALTER TABLE Users
ADD CONSTRAINT CH_UsernameIsAtLeast3Symbol
CHECK(LEN([Username]) >= 3);