CREATE DATABASE SoftUni

CREATE TABLE Towns
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(30) NOT NULL
)

CREATE TABLE Addresses
(
	Id INT PRIMARY KEY IDENTITY,
	AddressText VARCHAR(30) NOT NULL,
	TownId INT NOT NULL CONSTRAINT FK_AddressTownId_TownId FOREIGN KEY REFERENCES Towns(Id)
)

CREATE TABLE Departments
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(30) NOT NULL
)

CREATE TABLE Employees
(
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(50) NOT NULL,
	MiddleName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	JobTitle NVARCHAR(50),
	DepartmentId INT NOT NULL CONSTRAINT FK_EmployeeDepartmentId_DepartmentId FOREIGN KEY REFERENCES Departments(Id),
	HireDate NVARCHAR(50),
	Salary DECIMAL(7,2) NOT NULL,
	AddressId INT CONSTRAINT FK_EmployeeAddressId_AddressId FOREIGN KEY REFERENCES Addresses(Id)
)